<?php  //[STAMP] 5aef6e675ce8bdf8aa2a1d0c51a5d2be
namespace execut\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait CodeGuyActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
