<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 11/15/17
 * Time: 12:14 PM
 */

namespace execut\actions\widgets;


use execut\yii\jui\WidgetTrait;
use yii\helpers\Html;

class DynaGrid extends \kartik\dynagrid\DynaGrid
{
    use WidgetTrait;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        Html::addCssClass($this->options, $this->getDefaultCssClass());
        $this->_registerBundle();
        return parent::run();
    }
}