<?php
/**
 * Created by PhpStorm.
 * User: execut
 * Date: 10/18/17
 * Time: 2:56 PM
 */

namespace execut\actions\action;


use execut\actions\TestCase;
use yii\db\ActiveRecord;

class ModelsFinderTest extends TestCase
{
    public function testFind() {
        $modelsFinder = new ModelsFinder([
            'modelClass' => TestModel::class,
            'actionParams' => [
                'get' => [
                    'id' => 1,
                ],
            ],
        ]);
        $model = $modelsFinder->find();
        $this->assertInstanceOf(TestModel::class, $model);
        $this->assertEquals([
            'id' => 1,
        ], $model->findAttributes);
    }
}

class TestModel extends ActiveRecord {
    public $findAttributes = null;
    public $id = 1;
    public static function primaryKey($asArray = false)
    {
        return 'id'; // TODO: Change the autogenerated stub
    }

    public static function find()
    {
        return new self;
    }

    public function andWhere($attributes) {
        $this->findAttributes = $attributes;

        return $this;
    }

    public function one() {
        return $this;
    }
}